name: Main CI

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'The username of the user to fetch the repositories'
        required: true

jobs:
  build:
    environment: coding-challenge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          echo "Build with Maven"

      - name: Logging
        run: echo ${{ github.event.inputs.username }}

      - name: Fetch repo list
        run: |
          echo "Fetch repo list"